name: flow-merge
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10.13
  - pydantic=2.4.2
  - pyyaml=6.0.1
  - transformers=4.38.1
  - pytorch=2.2.1
  - pytorch-cuda=12.1
  - safetensors=0.4.2
  - peft=0.9.0
  - accelerate=0.27.2
  - pip=24.0
  - pip:
      - ipykernel==6.25.2
      - ruff==0.2.0
      - pre-commit==3.5.0
      - pyright==1.1.347
      - notebook==7.0.6
      - pytest==8.0.0
      - jupyter==1.0.0
      - huggingface-hub==0.21.1
      - isort==5.13.2
